version: '3'

services:
  db_postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=main_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"

  ocesql:
    build:
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      db_postgres:
        condition: service_started
    logging:
      driver: none
