name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run Docker
        run: |
         docker compose up -d
         docker ps
         docker attach open-cobol-esql-ocesql-1

