name: GitHub Actions Demo
on: [push]
         
jobs:
  pmd-code-scan:
    runs-on: ubuntu-latest
    
        # `container-job` で実行するサービスコンテナ
    services:
      # サービスコンテナへのアクセスに使用されるラベル
      postgres:
        # Docker Hub のイメージ
        image: postgres
        # postgres のパスワードを入力する
        env:
          POSTGRES_PASSWORD: postgres
        # postgres が起動するまで待機するようにヘルスチェックを設定する
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
          
      - name: Run tests
        run: |
          # install opensource COBOL
          sudo apt-get install -y gcc build-essential make bison flex libgmp3-dev libncurses5-dev libncursesw5-dev
          sudo apt-get install -y autoconf diffutils
          sudo apt-get install -y gzip         
          pwd
          cd 
          mkdir opt
          chmod -R 777 opt/
          cd opt


          curl -L -o opensource-cobol-1.5.2J.tar.gz https://github.com/opensourcecobol/opensource-cobol/archive/v1.5.2J.tar.gz
          ls
          tar zxvf opensource-cobol-1.5.2J.tar.gz
          ls
          cd opensource-cobol-1.5.2J/vbisam/
          ./configure --prefix=/usr/
          sudo make install
          cd /opensource-cobol-1.5.2J
          ./configure --prefix=/usr/ --with-vbisam
          sudo make install
          cd /
          rm -rf opensource-cobol-1.5.2J opensource-cobol-1.5.2J.tar.gz
          
          # install OCESQL
          curl -L -o Open-COBOL-ESQL-1.2.tar.gz https://github.com/opensourcecobol/Open-COBOL-ESQL/archive/v1.2.tar.gz
          tar zxvf Open-COBOL-ESQL-1.2.tar.gz
          cd /Open-COBOL-ESQL-1.2
          ./configure --prefix=/usr/
          make install
          cd /
          rm -rf Open-COBOL-ESQL-1.2 Open-COBOL-ESQL-1.2.tar.gz

          
          
          psql
          cd tests
          make clean
          make
          ./basic
