name: GitHub Actions Demo
on: [push]
         
jobs:
  pmd-code-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Install OCESQL
        run: |
          ./configure
          make AUTOCONF=: AUTOHEADER=: AUTOMAKE=: ACLOCAL=:
          make install AUTOCONF=: AUTOHEADER=: AUTOMAKE=: ACLOCAL=:
          
      - name: Run tests
        run: |
          psql
          cd tests
          make clean
          make
          ./basic
