name: GitHub Actions Demo
on: [push]
         
jobs:
  pmd-code-scan:
    runs-on: ubuntu-latest
    
        # `container-job` で実行するサービスコンテナ
    services:
      # サービスコンテナへのアクセスに使用されるラベル
      postgres:
        # Docker Hub のイメージ
        image: postgres
        # postgres のパスワードを入力する
        env:
          POSTGRES_PASSWORD: postgres
        # postgres が起動するまで待機するようにヘルスチェックを設定する
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
          
      - name: Run tests
        run: |
          # install opensource COBOL
          # dnf install -y gcc gcc-c++ make bison flex gmp-devel ncurses-devel zulu-14 unzip
          # dnf install -y autoconf diffutils
          pwd


          
          
          psql
          cd tests
          make clean
          make
          ./basic
